#!/bin/env sh

## Quickly restart the yabai launch agent
ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"


#focus space
hyper - 1 : yabai -m space --focus 1
hyper - 2 : yabai -m space --focus 2
hyper - 3 : yabai -m space --focus 3
hyper - 4 : yabai -m space --focus 4
hyper - 5 : yabai -m space --focus 5
hyper - 6 : yabai -m space --focus 6
hyper - 7 : yabai -m space --focus 7
hyper - 8 : yabai -m space --focus 8
hyper - 9 : yabai -m space --focus 9
hyper - 0 : yabai -m space --focus 10



# create desktop and follow focus - uses jq for parsing json (brew install jq)
cmd + alt - n : yabai -m space --create && \
                 index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
                 yabai -m space --focus "${index}"

alt - h : yabai -m window --warp west
alt - j : yabai -m window --warp south
alt - k : yabai -m window --warp north
alt - l : yabai -m window --warp east

# focus window in direction of focused window (options: north, east, south, west)
hyper - h : yabai -m window --focus west
hyper - j : yabai -m window --focus south
hyper - k : yabai -m window --focus north
hyper - l : yabai -m window --focus east


# Delete focused space and focus first space on display
hyper - backspace : yabai -m space --destroy

# Rotate the window tree clock-wise (options: 90, 180, 270 degree)
hyper - r : yabai -m space --rotate 90

# balance size of windows
shift + alt - 0 : yabai -m space --balance

# toggle whether the focused window should be tiled (only on bsp spaces)
hyper - m : yabai -m window --toggle float
alt - m : yabai -m window --toggle bsp

# send window to desktop and follow focus
alt - 1 : yabai -m window --space  1; yabai -m space --focus 1
alt - 2 : yabai -m window --space  2; yabai -m space --focus 2
alt - 3 : yabai -m window --space  3; yabai -m space --focus 3
alt - 4 : yabai -m window --space  4; yabai -m space --focus 4
alt - 5 : yabai -m window --space  5; yabai -m space --focus 5
alt - 6 : yabai -m window --space  6; yabai -m space --focus 6
alt - 7 : yabai -m window --space  7; yabai -m space --focus 7
alt - 8 : yabai -m window --space  8; yabai -m space --focus 8
alt - 9 : yabai -m window --space  9; yabai -m space --focus 9
alt - 0 : yabai -m window --space  10; yabai -m space --focus 10


# increase window size
hyper - h : yabai -m window --resize left:-30:0
hyper - j : yabai -m window --resize bottom:0:30
hyper - k : yabai -m window --resize top:0:-30
hyper - l : yabai -m window --resize right:30:0


